creation_rules:
  - path_regex: environments/(dev|prod)/secrets\.enc\.yaml$
    key_groups:
      - age:
          - age150en7zmjg970nnm54y7djzp6x0f926vgzuzkktam565z00dd4v4qtuee5q
          - age1avve00pacdr9s0l7j92pw7kxg7uq50evannaukucfwez8dyvz3zq7c92m0
